import 'dotenv/config';
import express from 'express';
import {StreamableHTTPServerTransport} from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import {makeServer} from './tools.js';
import {installAuth} from './auth.js';
import {installMobile} from './mobile.js';
import * as b from './browser.js';
const port=Number(process.env.PORT||3100),consentPort=Number(process.env.CONSENT_PORT||3101);
const host=process.env.CODESPACE_NAME;
const base=process.env.PUBLIC_BASE_URL || (host?`https://${host}-${port}.app.github.dev`:`http://127.0.0.1:${port}`);
const consentBase=process.env.CONSENT_BASE_URL || (host?`https://${host}-${consentPort}.app.github.dev`:`http://127.0.0.1:${consentPort}`);
const app=express(),privateApp=express();
app.disable('x-powered-by');privateApp.disable('x-powered-by');
app.use(express.json({limit:'256kb'}));app.use(express.urlencoded({extended:false,limit:'32kb'}));privateApp.use(express.json({limit:'64kb'}));privateApp.use(express.urlencoded({extended:false,limit:'32kb'}));
for(const a of [app,privateApp])a.use((_q,r,next)=>{r.set('Cache-Control','no-store').set('X-Content-Type-Options','nosniff');next();});
app.use((q,r,next)=>{if(q.headers.origin){let allowed=false;try{const u=new URL(q.headers.origin);allowed=q.headers.origin===base||(u.protocol==='https:'&&['chatgpt.com','chat.openai.com'].includes(u.hostname));}catch{}if(allowed===false)return r.status(403).json({error:'cross_origin_denied'});}next();});
const auth=await installAuth(app,privateApp,{base,consentBase});
installMobile(privateApp);
app.get('/health',(_q,r)=>r.status(b.isRunning()?200:503).json({ok:b.isRunning(),service:'live-browser-mcp',version:'0.1.0',browserReady:b.isRunning(),transport:'streamable-http',authentication:'oauth-pkce',mcp:base+'/mcp'}));
app.use('/mcp',auth);
app.post('/mcp',async(q,r)=>{const s=makeServer(),t=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});r.on('close',()=>{t.close().catch(()=>{});s.close().catch(()=>{});});try{await s.connect(t);await t.handleRequest(q,r,q.body);}catch{if(!r.headersSent)r.status(500).json({error:'mcp_request_failed'});}});
app.all('/mcp',(_q,r)=>r.status(405).set('Allow','POST').json({error:'method_not_allowed'}));
for(const a of [app,privateApp])a.use((_e,_q,r,_n)=>{if(!r.headersSent)r.status(500).json({error:'request_failed'});});
await b.getContext();
const publicServer=app.listen(port,'127.0.0.1',()=>console.log(`Live Browser MCP ready on port ${port}; OAuth required`));
const privateServer=privateApp.listen(consentPort,'127.0.0.1',()=>console.log(`Private approval port ${consentPort}`));
for(const signal of ['SIGINT','SIGTERM'])process.once(signal,async()=>{await b.shutdown();publicServer.close();privateServer.close();process.exit(0);});
