import express from 'express';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {mcpAuthRouter,getOAuthProtectedResourceMetadataUrl} from '@modelcontextprotocol/sdk/server/auth/router.js';
import {requireBearerAuth} from '@modelcontextprotocol/sdk/server/auth/middleware/bearerAuth.js';
import {InvalidGrantError,InvalidTokenError,InvalidRequestError} from '@modelcontextprotocol/sdk/server/auth/errors.js';
const scope='instagram:read',random=()=>crypto.randomBytes(32).toString('base64url'),hash=x=>crypto.createHash('sha256').update(x).digest('base64url'),now=()=>Math.floor(Date.now()/1000);
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const allowedRedirect='https://chatgpt.com/connector_platform_oauth_redirect';
export function installOAuth(app,origin,{adminPort=3001}={}){
 const issuer=new URL(origin);if(issuer.protocol!=='https:'||issuer.pathname!=='/'||issuer.search||issuer.hash)throw Error('PUBLIC_ORIGIN must be an HTTPS origin');const resource=new URL('/mcp',issuer),dir=process.env.SESSION_DIR||'./sessions';fs.mkdirSync(dir,{recursive:true,mode:0o700});const file=path.join(dir,'oauth.json');let db={clients:{},tokens:{}};if(fs.existsSync(file))db=JSON.parse(fs.readFileSync(file,'utf8'));const save=()=>{fs.writeFileSync(file+'.tmp',JSON.stringify(db),{mode:0o600});fs.renameSync(file+'.tmp',file)},pending=new Map(),codes=new Map(),csrf=random();const checkResource=r=>{if(r&&r.href!==resource.href)throw new InvalidRequestError('Unexpected resource')};
 const provider={clientsStore:{getClient:id=>db.clients[id],registerClient:client=>{if(!client.redirect_uris?.length||client.redirect_uris.some(u=>u!==allowedRedirect))throw new InvalidRequestError('Only the ChatGPT callback is allowed');const result={...client,client_id:random(),client_id_issued_at:now()};db.clients[result.client_id]=result;save();return result}},
 async authorize(client,params,res){checkResource(params.resource);if(params.redirectUri!==allowedRedirect)throw new InvalidRequestError('Unexpected redirect');if(params.scopes?.some(s=>s!==scope))throw new InvalidRequestError('Unsupported scope');const id=random();pending.set(id,{client,params,expires:now()+600,approved:false});res.set('Cache-Control','no-store').send(waitPage(id))},
 async challengeForAuthorizationCode(client,code){const x=codes.get(hash(code));if(!x||x.clientId!==client.client_id||x.expires<now())throw new InvalidGrantError('Expired authorization');return x.challenge},
 async exchangeAuthorizationCode(client,code,verifier,redirectUri,r){checkResource(r);const key=hash(code),x=codes.get(key);if(!x||x.clientId!==client.client_id||x.expires<now()||redirectUri!==x.redirectUri||!verifier||hash(verifier)!==x.challenge)throw new InvalidGrantError('Invalid authorization');codes.delete(key);const token=random();db.tokens[hash(token)]={clientId:client.client_id,scopes:[scope],expiresAt:now()+30*86400};save();return {access_token:token,token_type:'Bearer',expires_in:30*86400,scope}},
 async exchangeRefreshToken(){throw new InvalidGrantError('Reconnect to renew access')},async verifyAccessToken(token){const x=db.tokens[hash(token)];if(!x||x.expiresAt<now())throw new InvalidTokenError('Reconnect to authorize');return {...x,token,resource}},async revokeToken(client,req){const k=hash(req.token);if(db.tokens[k]?.clientId===client.client_id){delete db.tokens[k];save()}}};
 const waitPage=id=>'<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="3;url=/finish?id='+id+'"><title>Approve Instagram Analyzer</title><h1>Approve in your private Codespace</h1><p>Open private port 3001 and approve this ChatGPT connection. This page will continue automatically.</p><p>Request: '+id.slice(0,8)+'</p>';
 app.use(mcpAuthRouter({provider,issuerUrl:issuer,resourceServerUrl:resource,scopesSupported:[scope],resourceName:'Instagram Competitor Analyzer'}));app.get('/finish',(req,res)=>{res.set('Cache-Control','no-store');const id=String(req.query.id||''),x=pending.get(id);if(!x||x.expires<now())return res.status(410).send('Request expired. Reconnect in ChatGPT.');if(!x.approved)return res.send(waitPage(id));const code=random();codes.set(hash(code),{clientId:x.client.client_id,challenge:x.params.codeChallenge,redirectUri:x.params.redirectUri,expires:now()+120});pending.delete(id);const target=new URL(x.params.redirectUri);target.searchParams.set('code',code);if(x.params.state)target.searchParams.set('state',x.params.state);res.redirect(target.href)});
 const admin=express();admin.use(express.urlencoded({extended:false,limit:'8kb'}));admin.use((_q,res,next)=>{res.set({'Cache-Control':'no-store','Content-Security-Policy':"default-src 'none'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'",'X-Frame-Options':'DENY'});next()});admin.get('/',(_q,res)=>res.send('<!doctype html><meta charset="utf-8"><title>Private connection approval</title><h1>Instagram Analyzer - private approval</h1><p>Only approve the request you just started in ChatGPT. Access uses the saved Instagram session through three public research tools. No messages or posting tools.</p>'+([...pending].filter(([,x])=>x.expires>=now()&&!x.approved).map(([id,x])=>'<form method="post" action="/approve"><h2>Request '+esc(id.slice(0,8))+'</h2><p>Client: '+esc(x.client.client_name||'ChatGPT')+'</p><p>Callback: '+esc(x.params.redirectUri)+'</p><input type="hidden" name="id" value="'+id+'"><input type="hidden" name="csrf" value="'+csrf+'"><button>Approve this ChatGPT connection</button></form>').join('')||'<p>No requests. Start Connect in ChatGPT, then reload this page.</p>')));admin.post('/approve',(req,res)=>{if(req.body.csrf!==csrf)return res.sendStatus(403);const x=pending.get(req.body.id);if(!x||x.expires<now())return res.status(410).send('Expired request');x.approved=true;res.send('Approved. Return to the ChatGPT connection window. It will continue automatically.')});const listener=admin.listen(adminPort,'127.0.0.1');app.use('/mcp',requireBearerAuth({verifier:provider,requiredScopes:[scope],resourceMetadataUrl:getOAuthProtectedResourceMetadataUrl(resource)}));const cleanup=setInterval(()=>{for(const [k,v] of pending)if(v.expires<now())pending.delete(k);for(const [k,v] of codes)if(v.expires<now())codes.delete(k)},60000);cleanup.unref();return {provider,pending,listener,close:()=>{clearInterval(cleanup);listener.close()}};
}
